# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run_unit_tests:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - id: go-checks
      uses: sammorris66/go-checks@v1
      with:
        go-version: "1.23"
