# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run_checks:
    runs-on: ubuntu-latest

    steps:
    - id: go-checks
      uses: sammorris66/go-checks@2a1f6e32748a9d490a7b8128e1f080198c31cbe8
      with:
        go-version: '1.23'
